version: 2
build:
  tools:
    python: "3.10"
    nodejs: "18"
python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - examples
      - docs
conda:
  environment: docs/environment.yml
